version: "3.9"

services:
  # Имидж сервиса вэб приложения собранный из докен-файла
  web:
    build: .
    ports:
    - "127.0.0.1:5000:5000"
    networks:
    - net
    depends_on:
    - redis

  # Имидж сервиса Redis взятый готовым из риджестри
  redis:
    image: "redis:alpine"
    networks:
    - net
    volumes:
    - redis_data:/data

networks:
  net:
    driver: bridge

volumes:
  redis_data:
